### ISSUE TITLE
Make METviewer GUI run with Couchbase

### ISSUE THREAD

**Issue by venitahagerty** [NCAR/METviewer#100]
Make updates to GUI and CBAppDatabaseManager so that GUI can run with Couchbase.

**Comment by randytpierce** [comment]
I made a script that can take a mvservlet.log that has been set to debug context and that has captured a  session and create servlet test cases from the log.  These test cases can be used in the auto test environment and can be applied against either a mysql management system or a couchbase management system. Venita and I are currently working through the issues that these test cases have uncovered.

**Comment by randytpierce** [comment]
We have separated the build code from this code branch feature_100_cbgui and have built and tested this code with line plots that are defined in this https://docs.google.com/document/d/1IZ6vw0VgZ66HzQ2EU0Go47qoDAFObSVSLSwkj461m6U/edit
demo document. Not all plot types are supported yet and ongoing work is being carried on in a feature branch for issue 83.

As of December 12 this branch (feature_100_cbgui) has the code in dev merged into it.
This branch is ready for merging into dev with the functionality limited to the demo. The branch should only affect the db.CB* classes and the test package.

**Comment by venitahagerty** [comment]
Included in feature 83.
