### ISSUE TITLE
bootstrap output values depend on the input data order

### ISSUE THREAD

**Issue by TatianaBurek** [NCAR/METviewer#103]
If the order of initial date is changed the bootstrap statistics values can be different. 
The results of tests cases that use bootstrapping (  scorecard_agg_emc,  scorecard_agg_ncar ) might not match
To insure equal results initial data sorting by 'fcst_valid_beg' can be performed.
The sorting can take long time and decrease the performance

**Comment by TressaFowler** [comment]
I looked at the output, and I think this behavior makes sense and is not a bug. 

Bootstrap functions, with the same seed, with select the same cases (usually rows of data) to use. When data are in different order, the row number is the same but the data contained therein is different. Thus, to ensure identical results, the data must be in a set order (i.e. sorted). In general, sorting is not necessary for bootstrapped results, as the random selection of cases it makes it unnecessary. Also, sorting in R, especially for large data sets, is often slow. Thus, I do not recommend it in general. See me with questions.

Tressa
