### ISSUE TITLE
Enhance METviewer to read updated GRAD line type for met-8.1.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METviewer#118]
The GRAD line type from Grid-Stat has been enhanced in met-8.1 to make the gradient step size in the x and y directions configurable.  For this, we added new DX and DY output columns to the GRAD line type.  DX and DY are positive or negative integers specifying the gradient step size.

When aggregating multiple GRAD lines together, DX and DY must remain constant.  If not constant, error out.  However, this means that the user needs a way to specify which DX and DY values should be used.

Not exactly sure how we should handle this.  But it's analogous to only being able to aggregate RHIST lines when N_RANKS remains contant.

**Comment by JohnHalleyGotway** [comment]
When updating existing databases to add the DX and DY columns, set their value to 1 since that was the previously hard-coded value.

**Comment by JohnHalleyGotway** [comment]
Split this out into 2 separate issues.  (1) Read the DX/DY columns and load into table.  (2)... for next release... include their values in the processing logic and require that they remain constant.

**Comment by TatianaBurek** [comment]
issue  "Improve aggregation of multiple GRAD lines #129" is created
