### ISSUE TITLE
Do not insert file name in to the table if the file is empty

### ISSUE THREAD

**Issue by TatianaBurek** [NCAR/METviewer#119]

**Comment by venitahagerty** [comment]
Need to add this feature to Couchbase CBLoadDatabaseManager

**Comment by venitahagerty** [comment]
Changes added to CBLoadDatabaseManager. File name will not be inserted in to the table if the file is empty. As part of this change, upgraded to BoundedBufferedReader to match MySQL. Also, to resolve compile warning, removed line from build file that would not include (outdated) mariadb jar file, which is needed by scorecard even in the Couchbase version. Changes tested, committed, and pushed in feature branch feature_119_NoEmptyFile.
