### ISSUE TITLE
Bugs in mv2.5 when creating scorecards. MET-1004

### ISSUE THREAD

**Issue by lisagoodrich** [NCAR/METviewer#12]
Tina Kalb found bugs in mv2.5 when trying to regenerate scorecards that ran using mv2.4. Please look on dakota in: 
   /d3/projects/MET/MET_Help/kalb_data_20180524 

/d3/projects/METViewer/src/apps/METViewer/bin/mv_scorecard.sh scorecard_cam_cts_threshs_small.xml 

We get this error related to contour plots: 
==== Start Rscript error ==== 
Error: object 'isContourDiff' not found 

Adding neighborhood stats to the scorecard revealed this next error: 
==== Start Rscript error ==== 
Error: object 'boolAggGrad' not found 
Error: object 'boolAggVal1l2' not found 

We temporarily got around these errors by copying over the entire R_work/include directory and adding the following to the top of agg_stat.R: 
# JHG: Added these flags to get past runtime error from scorecards 
isContourDiff = FALSE; 
boolAggGrad = FALSE; 
boolAggVal1l2 = FALSE; 

We need to patch this ASAP for mv2.5. Also, John will need a rebuilt version of 2.5 in a docker container for using on the HWT machine bigbang2.

**Comment by TatianaBurek** [comment]
This problem was fixed sometime ago and can't be reproduced with the current version
