### ISSUE TITLE
Enhance METviewer to parse new FCST_UNITS and OBS_UNITS columns from STAT, MODE, and MTD output in met-8.1.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METviewer#125]

**Comment by TatianaBurek** [comment]
added fcst_units and obs_units to stat table.
Updated test data

**Comment by TatianaBurek** [comment]
We can't include units to the unique key because of the MySQL MariaDB limitation:
ERROR 1070 (42000): Too many key parts specified; max 16 parts allowed.
