### ISSUE TITLE
Display values for DIFF and symbols for statistical significance at the same time in the scorecard

### ISSUE THREAD

**Issue by TatianaBurek** [NCAR/METviewer#127]
Logan:
On a scorecard, is there a way to show the difference value (i.e., <stat>DIFF</stat>) and the statistical significance symbol?

For example,
<stat>DIFF_SIG</stat>
<view_symbol>TRUE</view_symbol>
<view_value>TRUE</view_value>
Gives me a scorecard with the symbols and p-values.

<stat>DIFF</stat>

<view_symbol>TRUE</view_symbol>
<view_value>TRUE</view_value>
Gives me a scorecard with the difference between the two models, but the “symbol” doesn’t match the statistical significance determined with the p-values.

we need to identify a project to pay for development.  Worried about the result being confusing/ambiguous.  Need to make sure the result is clearly labelled.

2780541

**Comment by JohnHalleyGotway** [comment]
Discussion during the telecon on 06/03/2019.  Enhance the existing legend or add a new one to describe what the symbol and the number represent on the scorecard.
This will require a change to the XML to specify the statistic for the symbol versus the number.

**Comment by TatianaBurek** [comment]
I added a new optional tags for specifying the stat for values and symbols:
<stat_value>DIFF</stat_value>
<stat_symbol>DIFF_SIG</stat_symbol> 
They can be used instead of <stat>
