### ISSUE TITLE
Performance diagram - XML upload and ordering of thresholds.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METviewer#136]
There seems to be 2 problems in the METviewer performance diagrams.

First, the XML upload feature is not working.  That attached XML doesn't load to the GUI well.

Second, the FCST_THRESH entries are not ordered numerically, and therefore, the resulting dots are connected in the wrong order.

In the attached plot, the purple dots should be form a smooth curve starting in the lower left corner.  But since their connected in the wrong order, it looks very jagged.

[plot_20190617_160833](https://user-images.githubusercontent.com/21087144/59620668-a9fa2200-90ea-11e9-9c1a-dd5f6f789055.png)
[plot_20190617_160833.xml.txt](https://github.com/NCAR/METviewer/files/3297927/plot_20190617_160833.xml.txt)

**Comment by TatianaBurek** [comment]
Was fixed for all plots on 05-May-2019

**Comment by TatianaBurek** [comment]
Fixed Values menu is fixed.
