### ISSUE TITLE
Load new DMAP line type created by Grid-Stat in MET version 9.0.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METviewer#161]
The Grid-Stat tool in MET version 9.0 creates a new output line type, DMAP, for distance map statistics.

Enhance the METviewer schema and mv_load logic to handle this new line type.

**Comment by JohnHalleyGotway** [comment]
[grid_stat_120000L_20050807_120000V_dmap.txt](https://github.com/NCAR/METviewer/files/3951799/grid_stat_120000L_20050807_120000V_dmap.txt)

**Comment by TatianaBurek** [comment]
Add DMAP stat to batch and UI
