### ISSUE TITLE
Load new MTD columns for MET version 9.0.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METviewer#164]
The columns for the MODE Time Domain output have been updated for MET version 9.0.

(1) Make time convolution amount configurable:
https://github.com/NCAR/MET/issues/1133

Add 4 new MTD header columns: FCST_T_BEG, FCST_T_END, OBS_T_BEG, OBS_T_END
These are integers indicating the beginning/ending of the time convolution window.  They appear in the header columns for all MTD text files.  For example...
   mtd_BASIC_20100517_010000V_2d.txt
   mtd_BASIC_20100517_010000V_3d_pair_cluster.txt
   mtd_BASIC_20100517_010000V_3d_pair_simple.txt
   mtd_BASIC_20100517_010000V_3d_single_cluster.txt
   mtd_BASIC_20100517_010000V_3d_single_simple.txt

These 4 header columns should appear in the METviewer GUI in the same menus as the other header columns (like FCST_RAD and FCST_THR).

(2) Add a user-configurable intensity percentile:
https://github.com/NCAR/MET/issues/1134

Add 1 new MTD data column: INTENSITY_* where * is a number between 0 and 100 and is specified by the user.  This is exactly the same logic as in the MODE output.  The last INTENSITY_ columns is configurable by the user.

**Comment by JohnHalleyGotway** [comment]
Sample MTD output containing these new columns can be see in recent runs of the nightly build on dakota in:
   /d3/projects/MET/MET_regression/develop/NB20200106/MET-develop/test_output/mtd

**Comment by TatianaBurek** [comment]
Done with loading and displaying new header columns in GUI
