### ISSUE TITLE
Enhance METviewer to read new RPS line type from Ensemble-Stat and Point-Stat.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METviewer#168]
The ERPS line type is being added for met-9.0.  METviewer needs to be enhanced to read this new line type.
https://github.com/NCAR/MET/issues/681

**Comment by JohnHalleyGotway** [comment]
As of 02/06/2020, we renamed this line type from ERPS to just RPS.  And we renamed the N_ENS column as N_PROB.

**Comment by TatianaBurek** [comment]
Add aggregation logic:
TOTAL = sum of the input TOTAL values
N_PROB = check that it remains constant
RPS_REL, RPS_RES, RPS_UNC, RPSS_SMPL = CANNOT BE AGGREGATED
RPS = Weighted average of input RPS values where TOTAL defines the weight
RPSS...

For each input line, use the following equation to compute RPS_CLIMO:
   RPS_CLIMO = RPS / ( 1.0 - RPSS )

Aggregate together the RPS values as weighted averages.
Aggregate together the RPS_CLIMO values as weighted averages.

Using the aggregated RPS and RPS_CLIMO, compute aggregated RPSS as:
   RPSS = 1.0 - ( RPS / RPS_CLIMO )

From https://github.com/NCAR/MET/blob/develop/met/src/libcode/vx_statistics/ens_stats.cc

RPSInfo & RPSInfo::operator+=(const RPSInfo &c) {
   RPSInfo r_info;

   if(n_prob != c.n_prob) {
      mlog << Error << "\nRPSInfo::operator+=() -> "
           << "the number of probability bins (\"N_PROB\") "
           << "must remain constant (" << n_prob << " != "
           << c.n_prob << ")!\n\n";
      exit(1);
   }

   r_info.fthresh = fthresh;
   r_info.othresh = othresh;
   r_info.n_pair  = n_pair + c.n_pair;
   r_info.n_prob  = n_prob;

   if(r_info.n_pair > 0) {

      // Aggregate RPS as a weighted average
      r_info.rps = (rps*n_pair + c.rps*c.n_pair) / r_info.n_pair;

      // Compute RPSS with external climatology
      if(!is_bad_data(rpscl) && !is_bad_data(c.rpscl)) {
         r_info.rpscl = (rpscl*n_pair + c.rpscl*c.n_pair) / r_info.n_pair;
         r_info.rpss  = (!is_eq(rpscl, 0.0) ?
                         1.0 - (r_info.rps / r_info.rpscl) :
                         bad_data_double);
      }
      else {
         r_info.rpscl = bad_data_double;
         r_info.rpss  = bad_data_double;
      }

      // The RPS components cannot be aggregated as a weighted average
      r_info.rps_rel   = bad_data_double;
      r_info.rps_res   = bad_data_double;
      r_info.rps_unc   = bad_data_double;
      r_info.rpss_smpl = bad_data_double;
   }

   assign(r_info);

   return(*this);
