### ISSUE TITLE
Y2 axis not working for DMAP measures in v2.12

### ISSUE THREAD

**Issue by TaraJensen** [NCAR/METviewer#172]
In testing plotting of DMAP measures today using mv_tatiana in the Test12 group, we noticed that we could not get a plot if Y2 was used.  Y2 plotting capability would be very useful for DMAP measures as they scale from near 1 (FOM) to Inf (Baddeley and Hausdorf).  The examples of all fields, including MED, present on Y1 axis and then no image available when MED is moved to Y2 can be found in these two xmls.

![plot_20200226_114803](https://user-images.githubusercontent.com/23195803/75380161-c5314a00-5893-11ea-8310-aa661f2fd9e1.png)

[plot_20200226_121509.xml.txt](https://github.com/NCAR/METviewer/files/4257768/plot_20200226_121509.xml.txt)

[plot_20200226_114803.xml.txt](https://github.com/NCAR/METviewer/files/4257776/plot_20200226_114803.xml.txt)

**Comment by TatianaBurek** [comment]
couldn't replicate
