### ISSUE TITLE
Debug difference curves in METviewer 3.0

### ISSUE THREAD

**Issue by TaraJensen** [NCAR/METviewer#174]
I'm trying to produce a plot with a difference curve.  I can produce a plot with event equalization turned on for two models, but when I add the difference curve, no error is produced, no data is produced, and hence no lines show up on the plot.  This error occurred for both CTC and ECNT line types.  Didn't try any others. This pair of XMLs provide an example of what I'm talking about.

![image](https://user-images.githubusercontent.com/23195803/77261789-b8b3cd80-6c56-11ea-9a1d-7dea02167bd1.png)

And a screenshot of no R data available

![image](https://user-images.githubusercontent.com/23195803/77261807-e731a880-6c56-11ea-9497-918f8a357eb6.png)

**Comment by TatianaBurek** [comment]
I rerun the plot with the difference curve and could not reproduce the screen shot you attached to the GitHub issue.
What I got is 'no plot' image and an error message  indicating that :
"Error: Derived curve can't be calculated. Multiple values for one valid date/fcst_lead"

**Comment by TaraJensen** [comment]
Operator error. Tatiana - you may close.
