### ISSUE TITLE
Add "package download" option 

### ISSUE THREAD

**Issue by davidfillmore** [NCAR/METviewer#176]
John:
<br/>
"We currently have an option for "dump points". One idea is to add another option for "package download".  After completing the plot, it&#39;d call a script to gather all the files related to that plot, maybe edit the paths in the rscript, and put them all into a tarball, along with the include directory.  The we&#39;d serve up a link to that tarball."
<i>[MET-791] created by tatiana</i>

**Comment by TaraJensen** [comment]
Moved to METviewer issues
