### ISSUE TITLE
Add support for ANOM_CORR_RAW which is new in the CNT line type for met-9.1.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METviewer#194]
[point_stat_GRIB1_NAM_GDAS_MASK_SID_120000L_20120409_120000V.stat.txt](https://github.com/NCAR/METviewer/files/4948898/point_stat_GRIB1_NAM_GDAS_MASK_SID_120000L_20120409_120000V.stat.txt)

## Describe the Enhancement ##
In met-9.1, we added new columns for uncentered anomaly correlation (called ANOM_CORR_RAW) to the CNT line type as described in this GitHub issue:
https://github.com/NCAR/MET/issues/1399

This adds 5 new columns named ANOM_CORR_RAW, ANOM_CORR_RAW_NCL, ANOM_CORR_RAW_NCU, ANOM_CORR_RAW_BCL, and ANOM_CORR_RAW_BCU.

This issue is to update METviewer as follows:
(1) Update the loader for met-9.1 CNT lines to include the 5 new columns.
(2) Update the plotting code to be able to plot the new ANOM_CORR_RAW statistic.
(3) Add code to derive ANOM_CORR_RAW from SAL1L2 partial sums. I've included the code to compute it below.
(4) Ensure that it appears in the list of stats in the GUI and can be included in scorecards.

```
compute_anom_corr_raw(double ffa, double ooa, double foa) {
   double v, c; 

   v = ffa*ooa;

   // Check for square root of negative number
   if(v < 0) {
      c = bad_data_double;
   }
   else {
      c = foa/sqrt(v);

      // Check the computed range
           if(c >  1) c =  1.0;
      else if(c < -1) c = -1.0;
   }

   return(c);
}
``` 

Here is a sample output file: 
[point_stat_GFS_CLIMO_1.0DEG_120000L_20120409_120000V_cnt.txt](https://github.com/NCAR/METviewer/files/4865888/point_stat_GFS_CLIMO_1.0DEG_120000L_20120409_120000V_cnt.txt)

### Acceptance Testing ###
After adding the functionality to derive ANOM_CORR_RAW from existing SAL1L2 partial sums, ask Binbin Zhou to test that derivation to make sure it matches VSDB results.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by TatianaBurek** [comment]
MET version 9.1 has not been released yet. Based on our emails, when we release it the CNT line type for 9.1 will include 3 new columns at the end of that line: ANOM_CORR_RAW, ANOM_CORR_RAW_BCL and ANOM_CORR_RAW_BCU. Any existing 9.1 output files should be discarded because they are only for development and testing purposes.

John

**Comment by TatianaBurek** [comment]
Added ANOM_CORR_RAW statistic to  "one perfect score stat" group

**Comment by TatianaBurek** [comment]
rename ANOM_CORR_RAW to ANOM_CORR_UNCNTR
