### ISSUE TITLE
Enhance METviewer to plot new CNT columns for the Scatter Index.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METviewer#317]
## Describe the Enhancement ##
dtcenter/MET#1843 adds 3 new columns to the CNT line type (SI, SI_BCL, and SI_BCU), for Scatter Index with bootstrap lower and upper limits. This new output is in MET version 10.1.0 and will be included in the MET version 10.1.0 beta2 development release.

The equation for the Scatter Index is very easy: SI = RMSE / OBAR

Like many other CNT statistics, SI is derivable from the SL1L2 line type. It should be handled in the same way that other CNT statistics, like RMSE, are handled.

Related METdatadb issue:
https://github.com/dtcenter/METdatadb/issues/61

Related METcalcpy issue:
https://github.com/dtcenter/METcalcpy/issues/108

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by TatianaBurek** [comment]
the data is on kiowa
/d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta2/feature_1843/MET-feature_1843_scatter_index/test_output/grid_stat/grid_stat_GRIB2_NAM_RTMA_120000L_20120409_120000V.stat
[grid_stat_GRIB2_NAM_RTMA_120000L_20120409_120000V.stat.txt](https://github.com/dtcenter/METviewer/files/6971108/grid_stat_GRIB2_NAM_RTMA_120000L_20120409_120000V.stat.txt)
