### ISSUE TITLE
Enable the user to specify a plotting job name. MET-504

### ISSUE THREAD

**Issue by lisagoodrich** [NCAR/METviewer#39]
As of mv_1_1, the METViewer web GUI creates plots named "plot_YYYYMMDD_HHMMSS.png". Users often go through several iterations in the process of making one plot and doing so causes several version of the plot to show up in the history. Suggest adding a way for the user to specify the plotting job name to be used in place of "plot_timestamp". Each time that job is run, it'd over-write the existing output. That same job name should be used in the file names for the plot, xml, log, rscript, data, and sql. Also, when displaying the plot history along the left side, sort the files by revision date rather than in alphabetical order... that may already be happening, but we just need to check. 

Need to check how would this affect the <cache_agg_stat> option? That's intended to avoid doing bootstrapping over and over again. If the same plot name is used, it'd be easy to check if that bootstrapping output file already exists for that job name.

**Comment by JohnHalleyGotway** [comment]
This was discussed again on 11/05/2018, add it as the first box under the "Titles & Labels" tab.  By default, when specifying the plot name, have revisions overwrite any existing data.  Consider adding a true/false checkbox to "Keep Revisions" and add a .0, .1, .2... suffix to track them.
