### ISSUE TITLE
Error during calculating CNT and CNTSUM statistics (Difference option) for MODE MET-322

### ISSUE THREAD

**Issue by lisagoodrich** [NCAR/METviewer#47]
During calculation CNT and CNTSUM statistics (Difference option) for MODE METViever gives this error: 
"FUNCTION s.COUNT does not exist. " 

The problem is in invalid SQL statement for calculating statistics. 
SELECT s.model, s.fcst_init, s.fcst_valid, s.fcst_lead, s.fcst_var, s.object_id, s.object_cat, 'CNT_DAA' stat_name, s.COUNT(object_id) - s2.COUNT(object_id) stat_value FROM mode_single s, mode_single2 s2. 
MySQL functions COUNT and SUM can't be accessed using the table name

**Comment by TatianaBurek** [comment]
METviewer calculates the difference only for MODE Ratio stat
