### ISSUE TITLE
Bug in Taylor Diagram in METviewer

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METviewer#75]
I tried using the attached XML to make a Taylor diagram which resulted in the following Rscript error message:

failed to run plot plot_20181002_025658 - reason: R error: ==== Start Rscript error ==== Error in library(plotrix) : there is no package called 'plotrix' Calls: source -> withVisible -> eval -> eval -> library Execution halted ==== End Rscript error ====
[plot_20181002_025658.xml.txt](https://github.com/NCAR/METviewer/files/2436327/plot_20181002_025658.xml.txt)

**Comment by TatianaBurek** [comment]
R package "plotrix' was missing on mandan.
It is installed now and this error message is gone.
