### ISSUE TITLE
Handle Series and Ens_ss plots in Couchbase

### ISSUE THREAD

**Issue by venitahagerty** [NCAR/METviewer#83]
In MVBatch, jobManager, and CBAppDatabaseManager - test Series plots with more Couchbase data and modify Couchbase code to handle Ens_ss plots.

**Comment by venitahagerty** [comment]
Merged dev into this branch, including separating out the password from Databaseinfo, removal of id tag, and the new build code.

**Comment by TatianaBurek** [comment]
Merged dev into this branch with manual conflict resolutions.
