### ISSUE TITLE
Exploration for method of tracking performance within MVBatch

### ISSUE THREAD

**Issue by randytpierce** [NCAR/METviewer#89]
investigating

**Comment by TatianaBurek** [comment]
I added new and rearrange existing execution time measurements and log messages

**Comment by randytpierce** [comment]
should this code be merged into feature82?

**Comment by TatianaBurek** [comment]
I created a separate brunch for this issue : feature_89_tracking_performance
I will merge this brunch to dev when I'm done updating execution time calculation and statements
