### ISSUE TITLE
fix "GROUP BY' clause (   Hist, Roc and Reliability)

### ISSUE THREAD

**Issue by TatianaBurek** [NCAR/METviewer#97]
To accommodate changes in newer MySQL versions the fix was introduced in issue #82.
Randy suggested and implemented a fix by adding all  of the select fields to the "GROUP BY' clause.
The queries created with this fix return different set of data than the old ones.

Database mv_clue_2016
OLD query
SELECT
model,
fcst_init,
fcst_valid,
fcst_lead,
fcst_var,
object_id,
object_cat,
'CNT_FSA' stat_name,
COUNT(object_id) stat_value
FROM
mode_header ,
mode_obj_single ,
mode_cts
WHERE
fcst_valid IN ('2016-05-04 01:00:00', '2016-05-04 02:00:00', '2016-05-04 03:00:00', '2016-05-04 04:00:00', '2016-05-04 05:00:00')
AND model IN ('core01_hwt')
AND fcst_lead IN ('10000', '20000')
AND fcst_var = 'APCP_01'
AND fcst_flag = 1
AND simple_flag = 1 AND mode_obj_single.mode_header_id = mode_header.mode_header_id
AND mode_cts.mode_header_id = mode_obj_single.mode_header_id
AND mode_cts.field = 'OBJECT'
GROUP BY fcst_lead, model,fcst_valid;
returns 
+------------+---------------------+---------------------+-----------+----------+-----------+------------+-----------+------------+
| model      | fcst_init           | fcst_valid          | fcst_lead | fcst_var | object_id | object_cat | stat_name | stat_value |
+------------+---------------------+---------------------+-----------+----------+-----------+------------+-----------+------------+
| core01_hwt | 2016-05-04 00:00:00 | 2016-05-04 01:00:00 |     10000 | APCP_01  | F001      | CF007      | CNT_FSA   |          8 |
| core01_hwt | 2016-05-04 00:00:00 | 2016-05-04 02:00:00 |     20000 | APCP_01  | F001      | CF000      | CNT_FSA   |         11 |
+------------+---------------------+---------------------+-----------+----------+-----------+------------+-----------+------------+
2 rows in set (0.00 sec)

and a new query

SELECT
model,
fcst_init,
fcst_valid,
fcst_lead,
fcst_var,
object_id,
object_cat,
'CNT_FSA' stat_name,
COUNT(object_id) stat_value
FROM
mode_header ,
mode_obj_single ,
mode_cts
WHERE
fcst_valid IN ('2016-05-04 01:00:00', '2016-05-04 02:00:00', '2016-05-04 03:00:00', '2016-05-04 04:00:00', '2016-05-04 05:00:00')
AND model IN ('core01_hwt')
AND fcst_lead IN ('10000', '20000', '30000')
AND fcst_var = 'APCP_01'
AND fcst_flag = 1
AND simple_flag = 1 AND mode_obj_single.mode_header_id = mode_header.mode_header_id
AND mode_cts.mode_header_id = mode_obj_single.mode_header_id
AND mode_cts.field = 'OBJECT'
GROUP BY
fcst_lead,
model , fcst_valid ,fcst_init ,fcst_var, object_id, object_cat;

returns 32 rows

**Comment by TatianaBurek** [comment]
The test use case 'series_mode_attr' is failed.
Old query:
SELECT
  model,
  fcst_init,
  fcst_valid,
  fcst_lead,
  fcst_var,
  HOUR(fcst_init) init_hour,
  object_id,
  object_cat,
  'CNT_FCA' stat_name,
  COUNT(object_id) stat_value
FROM
  mode_header ,
  mode_obj_single ,
  mode_cts 
WHERE
  HOUR(fcst_init) IN ('12')
  AND model IN ('AFWAOCv3.5.1_d01', 'NoahMPv3.5.1_d01')
  AND fcst_lead IN ('90000', '120000', '210000', '330000')
 AND  fcst_var = 'APCP_03'
  AND fcst_flag = 1
  AND simple_flag = 0  AND mode_obj_single.mode_header_id = mode_header.mode_header_id
  AND mode_cts.mode_header_id = mode_obj_single.mode_header_id
  AND mode_cts.field = 'OBJECT'
GROUP BY
  fcst_lead,
  model,
  init_hour  , fcst_valid
Returns 23 rows

New query:
SELECT
  model,
  fcst_init,
  fcst_valid,
  fcst_lead,
  fcst_var,
  HOUR(fcst_init) init_hour,
  object_id,
  object_cat,
  'CNT_FCA' stat_name,
  COUNT(object_id) stat_value
FROM
  mode_header ,
  mode_obj_single ,
  mode_cts 
WHERE
  HOUR(fcst_init) IN ('12')
  AND model IN ('AFWAOCv3.5.1_d01', 'NoahMPv3.5.1_d01')
  AND fcst_lead IN ('90000', '120000', '210000', '330000')
 AND  fcst_var = 'APCP_03'
  AND fcst_flag = 1
  AND simple_flag = 0  AND mode_obj_single.mode_header_id = mode_header.mode_header_id
  AND mode_cts.mode_header_id = mode_obj_single.mode_header_id
  AND mode_cts.field = 'OBJECT'
GROUP BY
  fcst_lead,
  model,
  init_hour  , fcst_valid  ,fcst_init  ,fcst_var, object_id, object_cat
Returns 236 rows

**Comment by randytpierce** [comment]
I am not sure that I have this database. Is it possible that I can get a backup of this data?

**Comment by TatianaBurek** [comment]
The queries from the second comment are generated for the test database.

**Comment by TatianaBurek** [comment]
I'm working on modifying queries for Hist, Roc and Reliability plots.
Mode and mode-td queries are more complex and will be done for the next (v.3.0 ??) release

**Comment by randytpierce** [comment]
I understand a little more. Of course our server is not configured to allow the old query. Therefore I never saw the old results for the failing queries, just failure messages. I had captured new test results and the new test results, of course, passed. My understanding of the mysql group by clause was naive. It causes us to get extra results. I need to understand this further and see if there is a way to restrict the results in a way that the query can still be dynamically generated.

**Comment by TatianaBurek** [comment]
Fix was implemented for Hist, Roc and Reliability.
I will create a new issue for MODE and MODE-TD
